### ISSUE TITLE
Feature Request: Add Documentation and Examples

### ISSUE THREAD

**Issue by kookma** [lollcat/RL-Process-Design#14]
Would you please add some documentation shows how this repo can be used and if possible some examples to see how it works.
Can we use this repo with DWSIM?

**Comment by lollcat** [comment]
Hello! Thank you for the request! I think a good starting place example is  https://github.com/lollcat/RL-Process-Design/blob/master/Discrete/PFR%20or%20CSTR/Agent.ipynb. I have updated the list of dependencies so you should be able to replicate the results. I am currently very busy with work, but will try my best to add documentation when I get some free moments. Let me know if you find the example helpful! 

In this repository, I wrote the simulator from scratch in python, so it cannot be used with DWSIM. https://github.com/lollcat/DistillationTrain-Gym does however include integration with COCO simulator.
